version: "3.7"

services:
  postgres:
    image: postgres:16.2-alpine3.19
    container_name: db-pass-in
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=passindb
    networks:
      - passinnet

  api-pass-in:
    build:
      context: .
    container_name: api-pass-in
    ports:
      - 3001:3333
    environment:
      - DATABASE_URL=postgresql://admin:admin@postgres:5432/passindb
      - API_BASE_URL=http://localhost:3333
      - PORT=3333
    depends_on:
      - postgres
    networks:
      - passinnet

networks:
  passinnet:
    driver: bridge
